{
 "title": "Beacons info",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "Temperature in degrees Celsius as a function of date and time",
   "gridPos": { "h": 22, "w": 23, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "beacons_data",
     "rawSql": "SELECT\r\n  t.FoundTimestamp AS \"time\",\r\n  t.TemperatureCelsius AS \"\",\r\n  b.DeviceIdentifier AS \"metric\"   \r\nFROM beacons_data.Temperature t\r\nJOIN beacons_data.Beacons b ON t.BeaconId = b.Id \r\nORDER BY t.FoundTimestamp ASC"
    }
   ]
  },
  {
   "title": "Received Signal Strength Indicator",
   "type": "timeseries",
   "description": "Rssi in dBm as a function of date and time",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "dataset": "beacons_data",
     "rawSql": "SELECT\r\n  t.FoundTimestamp AS \"time\",\r\n  t.SignalStrengthdBm AS \"\",\r\n  b.DeviceIdentifier AS \"metric\"   \r\nFROM beacons_data.Rssi t\r\nJOIN beacons_data.Beacons b ON t.BeaconId = b.Id \r\nORDER BY t.FoundTimestamp ASC"
    }
   ]
  },
  {
   "title": "Battery level",
   "type": "timeseries",
   "description": "Battery level in percent as a function of date and time",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "beacons_data",
     "rawSql": "SELECT\r\n  t.FoundTimestamp AS \"time\",\r\n  t.BatteryLevelPercent AS \"\",\r\n  b.DeviceIdentifier AS \"metric\"   \r\nFROM beacons_data.Battery t\r\nJOIN beacons_data.Beacons b ON t.BeaconId = b.Id \r\nORDER BY t.FoundTimestamp ASC"
    }
   ]
  },
  {
   "title": "Beacons list",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 44 },
   "targets": [
    {
     "dataset": "beacons_data",
     "rawSql": "SELECT DeviceBleAddress AS \"Device BLE Address\", DeviceIdentifier AS \"Device UUID\", Id AS \"Database UUID\" FROM beacons_data.Beacons LIMIT 50 "
    }
   ]
  }
 ]
}