// <auto-generated />
using System;
using BeaconTelemetryHub.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeaconTelemetryHub.Database.Migrations
{
    [DbContext(typeof(BeaconDbContext))]
    [Migration("20260119212351_AddedRssi")]
    partial class AddedRssi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BeaconTelemetryHub.Database.Models.Battery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary Key");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BatteryLevelPercent")
                        .HasColumnType("double")
                        .HasComment("Battery level in %");

                    b.Property<double>("BatteryVoltageMillivolts")
                        .HasColumnType("double")
                        .HasComment("Battery level in millivolts");

                    b.Property<int>("BeaconId")
                        .HasColumnType("int")
                        .HasComment("Beacon foreign key");

                    b.Property<DateTimeOffset>("FoundTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasComment("Data found timestamp");

                    b.HasKey("Id");

                    b.HasIndex("BeaconId");

                    b.ToTable("Battery");
                });

            modelBuilder.Entity("BeaconTelemetryHub.Database.Models.Beacon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary Key");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceBleAddress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("Beacon Ble address");

                    b.Property<string>("DeviceIdentifier")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasComment("Beacon manufacturer UUID");

                    b.HasKey("Id");

                    b.HasIndex("DeviceIdentifier")
                        .IsUnique();

                    b.ToTable("Beacons");
                });

            modelBuilder.Entity("BeaconTelemetryHub.Database.Models.Rssi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary Key");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BeaconId")
                        .HasColumnType("int")
                        .HasComment("Beacon foreign key");

                    b.Property<DateTimeOffset>("FoundTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasComment("Data found timestamp");

                    b.Property<short>("SignalStrengthdBm")
                        .HasColumnType("smallint")
                        .HasComment("Rssi value in dBm");

                    b.HasKey("Id");

                    b.HasIndex("BeaconId");

                    b.ToTable("Rssi");
                });

            modelBuilder.Entity("BeaconTelemetryHub.Database.Models.Temperature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary Key");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BeaconId")
                        .HasColumnType("int")
                        .HasComment("Beacon foreign key");

                    b.Property<DateTimeOffset>("FoundTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasComment("Data found timestamp");

                    b.Property<double>("TemperatureCelsius")
                        .HasColumnType("double")
                        .HasComment("Temperature report by beacon");

                    b.HasKey("Id");

                    b.HasIndex("BeaconId");

                    b.ToTable("Temperature");
                });

            modelBuilder.Entity("BeaconTelemetryHub.Database.Models.Battery", b =>
                {
                    b.HasOne("BeaconTelemetryHub.Database.Models.Beacon", "Beacon")
                        .WithMany()
                        .HasForeignKey("BeaconId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Beacon");
                });

            modelBuilder.Entity("BeaconTelemetryHub.Database.Models.Rssi", b =>
                {
                    b.HasOne("BeaconTelemetryHub.Database.Models.Beacon", "Beacon")
                        .WithMany()
                        .HasForeignKey("BeaconId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Beacon");
                });

            modelBuilder.Entity("BeaconTelemetryHub.Database.Models.Temperature", b =>
                {
                    b.HasOne("BeaconTelemetryHub.Database.Models.Beacon", "Beacon")
                        .WithMany()
                        .HasForeignKey("BeaconId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Beacon");
                });
#pragma warning restore 612, 618
        }
    }
}
